### ISSUE TITLE
Need an example

### ISSUE THREAD

**Issue by djshapiro** [NiGhTTraX/react-docs-cosmos-proxy#10]
Hi, I'd like to use this plugin to integrate react-docgen with cosmos, but I'm too new to cosmos to understand why it isn't working for me. It'd be nice to look at an example project, so I could see how the proxy and babel config look and also so I could run the project to look at the docs. Can you point me to an example project on github that uses this plugin successfully?

**Comment by NiGhTTraX** [comment]
Hi @djshapiro, this project itself uses the proxy. You can check the [.babelrc](https://github.com/NiGhTTraX/react-docs-cosmos-proxy/blob/16a2ed2a88c162588ead666eda4799172b03db4b/playground/components/acceptance/.babelrc) and [cosmos.proxies.js](https://github.com/NiGhTTraX/react-docs-cosmos-proxy/blob/master/playground/cosmos.proxies.js) and of course run `npm run playground` to see it in action. Now to be fair I haven't touched the code in a while so I hope I didn't leave it in a broken state. The project is definitely unfinished but it should be relatively easy to extend the [config for the DocsTable component](https://github.com/NiGhTTraX/react-docs-cosmos-proxy/blob/16a2ed2a88c162588ead666eda4799172b03db4b/src/index.jsx#L16-L25) with your own components and then [pass it to the proxy](https://github.com/NiGhTTraX/react-docs-cosmos-proxy/blob/16a2ed2a88c162588ead666eda4799172b03db4b/src/index.jsx#L35) (check the code docstrings for guidance).

**Comment by djshapiro** [comment]
Thanks, that was very helpful!
